### ISSUE TITLE
It will not work if Chrome is not installed

### ISSUE THREAD

**Issue by Mi10s** [lirantal/is-website-vulnerable#12]
I've tried to run scan on my Linux Mint 19.2 Cinnamon and error was thrown at the terminal.

Can you please add in a README file that Chrome is necessary in order to make scan possible?

**Comment by lirantal** [comment]
Definitely. Good point 👍 

@Mi10s would you like to submit a PR that updates the README's `Install` section with this requirement note?

**Comment by Mi10s** [comment]
Yes, I'll be glad to add PR with `Install` section update.

**Comment by vadistic** [comment]
Does not seem to work for me on manjaro linux :sob: 

But I'm guessing it's some `chrome-launcher` issue.

```log
{ Error: connect ECONNREFUSED 127.0.0.1:37017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 37017 }
```

**Comment by lirantal** [comment]
Do you have Chrome or Chromium installed?

**Comment by lirantal** [comment]
@vadistic @Mi10s if you get a chance to test it under Linux (and have Chrome or Chromium installed) then can you give it another try? I added some flags required for Linux OS to get chrome launched.

**Comment by Mi10s** [comment]
@lirantal Will do.

**Comment by lirantal** [comment]
thanks! 🙏

**Comment by Mi10s** [comment]
Just tested under Linux Ubuntu 16.04 (Chrome 77.0.3865.90) and it is working fine.

**Comment by lirantal** [comment]
yay, thanks for testing letting me know ❤️

**Comment by vadistic** [comment]
@lirantal Yes I did have chrome. You've fixed it. Works after update :tada:  Thank :)

**Comment by lirantal** [comment]
yay
