### ISSUE TITLE
Output breaks in ZSH

### ISSUE THREAD

**Issue by doncullen** [lirantal/is-website-vulnerable#18]
Current Behavior:
Displays certain characters incorrectly.  Missing font on my part, perhaps?

![image](https://user-images.githubusercontent.com/2024899/66296965-50457f80-e8b4-11e9-8f67-cfe23a96c8bd.png)

## Your Environment
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
node --version: v12.11.1
shell: /bin/bash (zsh)

Ran this using ConEmu (v190526 [64] {Preview}).  

Additional note: Ubuntu is running via WSL.  Windows version is Microsoft Windows [Version 10.0.18362.388]

**Comment by lirantal** [comment]
Good point. I'll see if it's possible to detect terminal support for these characters and have a fallback.

**Comment by seanhealy** [comment]
Just incase it helps I'm using zsh on MacOS 10.14.5 and not seeing the missing characters. Could still be a font or character set issue though. :)

**Comment by lirantal** [comment]
Uhmm, possibly related to ConEmu..?

**Comment by lirantal** [comment]
@doncullen could you run these 2 commands and tell me both of their exit status codes?

`npx supports-color-cli --16m` and `npx supports-color-cli --256`

**Comment by doncullen** [comment]
![image](https://user-images.githubusercontent.com/2024899/66427001-bdeacc00-e9d8-11e9-9052-f229efa73ba0.png)

**Comment by lirantal** [comment]
Oh sorry for missing that, you need to run `echo $?` after every command, so basically:

```
npx supports-color-cli --16m
echo $?
npx supports-color-cli --256
echo $?
```

**Comment by doncullen** [comment]
Ran it, --16m returned 1, --256 returned 0.

**Comment by lirantal** [comment]
Thanks that's useful. I'll see if we can find a way to detect if the terminal supports those escape characters that are being used and fallback to something else

**Comment by lirantal** [comment]
@doncullen looks like this is some issue with ConEmu that is actually supporting UTF8 but I think the font it has to render the chars doesn't map correctly. Can you check if using a different terminal works? or perhaps the settings on ConEmu? https://conemu.github.io/en/UnicodeSupport.html

Happy to know if you're able to figure out and what solved it

**Comment by lirantal** [comment]
I'll close for now but you're welcome to chime in and update.
