### ISSUE TITLE
Support Chromium as well as Chrome

### ISSUE THREAD

**Issue by unikitty37** [lirantal/is-website-vulnerable#22]
**Is your feature request related to a problem? Please describe.**
I have Chromium installed. I do not have Chrome installed, as I don't want the Google-specific stuff, and I don't want to agree to Google's TOS.

When I run `npx is-website-vulnerable http://example.com`, I get an `ERR_LAUNCHER_NOT_INSTALLED` message, despite the fact that Chromium is fully Chrome-compatible, and should work if the checker would only look for it before complaining.

I'm running Mac OS X 10.14.6 (18G95) with Chromium installed at `/Applications/Chromium.app`.

**Describe the solution you'd like**
Ideally, detection should be automatic:

* If Chromium is installed and Chrome is not installed, Chromium should be used.
* If Chromium and Chrome are both installed, it should be possible to configure which is used.

**Describe alternatives you've considered**
As this functionality appears to be provided by `chrome-launcher` (which I didn't notice when I initially opened the ticket — sorry!) auto-detection might not be possible without upstream changes.

However, a `--chrome-path` parameter, if provided, could provide the path to pass on to `chrome-launcher` via its `chromePath` parameter. That would allow Chromium users to at least get `is-website-vulnerable` to run…

**Comment by lirantal** [comment]
@unikitty37 sounds like you've worked out all the details and I like your suggestion of passing a CLI argument of `--chrome-path` and passing that over to chrome launcher. Would you like to submit a PR to address this?

**Comment by unikitty37** [comment]
I can look at it if I have time — but I fear that might not be for a while…

If anybody else fancies trying it in the meantime, I'm not going to get upset 😁

**Comment by lirantal** [comment]
@unikitty37 this is now supported thanks to @nopantsmonkey and a `--chromePath` CLI argument.
