### ISSUE TITLE
How to test for mobile & desktop pages for the same URL?

### ISSUE THREAD

**Issue by samarpanda** [lirantal/is-website-vulnerable#23]
Testing for mobile & desktop when they are using completely different setup. Any flags to use for screen-size / user agent / desktop|mobile?

**Comment by lirantal** [comment]
@samarpanda is there a specific user-agent that identifies a mobile client? if so, we could support a `--mobile` flag that will set it. We can also set a window size indeed.

Can you figure out the details for the above flags of a window size and user-agent that would be good to identify a mobile device? If so, and you'd like to make the change yourself I'd be happy to merge a Pull Request doing this.

**Comment by zivkaziv** [comment]
Hey, I would like to work on it.
What do you think about general flag of 

> --ua

?

**Comment by lirantal** [comment]
I think it might be too specific vs specifying `--mobile`.
The idea is that the flag will request a mobile version of the site, without someone needing to understand the internals of user agents, etc.

**Comment by zivkaziv** [comment]
So just make sure I got it right, `--mobile` will enable the flag `--emulated-form-factor` in lighthouse.
Is that correct?

**Comment by samarpanda** [comment]
> --emulated-form-factor         Controls the emulated device form factor (mobile vs. desktop) if not disabled                      [choices: "mobile", "desktop", "none"] [default: "mobile"]

Yes, as per the [lighthouse cli options doc](https://github.com/GoogleChrome/lighthouse#cli-options)

**Comment by lirantal** [comment]
Yep

**Comment by Z95** [comment]
Thanks guys, I’m planning to deliver during the weekend.. Sorry that it’s taking me forever

**Comment by zivkaziv** [comment]
I’m planning to deliver it during the weekend.. Sorry that it’s taking me forever

**Comment by lirantal** [comment]
@zivkaziv no worries at all and no rush, family and your well being comes first ❤️

**Comment by samarpanda** [comment]
@zivkaziv I can push one work in progress PR is you don't mind?

**Comment by samarpanda** [comment]
https://github.com/lirantal/is-website-vulnerable/pull/33

**Comment by zivkaziv** [comment]
Sure

**Comment by lirantal** [comment]
@zivkaziv is there anything else to do it in that PR from your side @zivkaziv ?

**Comment by zivkaziv** [comment]
Nope.
BTW, @samarpanda are you sure that `emulatedFormFactor` should be part of the opts, and not part of the lighthouseSettings?

**Comment by samarpanda** [comment]
I wanted to include the new flags in the readme. But it seems @zivkaziv has already added that to the readme. So, we don't need any documentation changes.

**Comment by lirantal** [comment]
Closed by #33

**Comment by lirantal** [comment]
Yep, looks good!
