### ISSUE TITLE
Add a loader while lighthouse scan runs

### ISSUE THREAD

**Issue by lirantal** [lirantal/is-website-vulnerable#3]
**Is your feature request related to a problem? Please describe.**
As it may take some time, fairly up to half a minute, to scan a website to detect used JS libs and their vulns, we could show a CLI loader to show that something is happening.

**Describe the solution you'd like**
Extra points if you want to be creative with the spinner ;-)

**Comment by ahmedkrmn** [comment]
Can you assign me this issue?

**Comment by lirantal** [comment]
Sure thing.
Would be happy if you could run your idea for a spinner so we could see together if its a good fit.

**Comment by lirantal** [comment]
closed by #13
