### ISSUE TITLE
Add detected libraries to the JSON output results

### ISSUE THREAD

**Issue by lirantal** [lirantal/is-website-vulnerable#30]
**Is your feature request related to a problem? Please describe.**
PR #21 added support for printing out detected JS libraries and their versions but they are provided if a JSON output is being used `--json`

**Comment by mixth** [comment]
Interested. Does this JSON structure look fine to you?
```
{
  "website": "https://example.com",
  ...
  "libraries": [
    {  "name": "", "version": "" }
  ]
}
```

**Comment by lirantal** [comment]
The current JSON output looks as follows:

```json
{
  "website": "https://www.foxnews.com/",
  "executionTime": "8592.97 ms",
  "totalVulnerabilities": 4,
  "result": [
    {
      "library": "jQuery@3.1.1",
      "severity": "Medium",
      "vulnerabilitiesCount": 1,
      "url": "https://snyk.io/vuln/npm:jquery?lh=3.1.1&utm_source=lighthouse&utm_medium=ref&utm_campaign=audit"
    },
    {
      "library": "Lo-Dash@4.17.4",
      "severity": "High",
      "vulnerabilitiesCount": 3,
      "url": "https://snyk.io/vuln/npm:lodash?lh=4.17.4&utm_source=lighthouse&utm_medium=ref&utm_campaign=audit"
    }
  ]
}
```

Ideally, we should have called the `result` field `vulnerabilities` and then we could add `libraries`. If we want to make that change we'd need to push a new major version out. Otherwise we can add `libraries` as another field next to `result` but it feels weird.

What do you think?

**Comment by mixth** [comment]
Yes, it does feel weird. Changing `result` to `vulnerabilities` is clearer and more understandable.

I'm not sure how we are going to do this. Should I make the change in the same PR?

**Comment by lirantal** [comment]
Yep, I agree. Make that change in the structure with your PR and we will mark it as a breaking change when I merge it to master.

**Comment by mixth** [comment]
One quick question. When there is no `result`, the existing behavior is to create `"result": "No JavaScript libraries detected with publicly known security vulnerabilities"`.

Would you like to have `libraries` behave the same?
like: `"libraries": "No JavaScript libraries detected"`

I prefer both to be an empty array over string though.

**Comment by lirantal** [comment]
Agree. Let's change them both to return empty arrays.
