### ISSUE TITLE
Inject lighthouse initialisation parameters

### ISSUE THREAD

**Issue by zivkaziv** [lirantal/is-website-vulnerable#34]
**Is your feature request related to a problem? Please describe.**
Every new lighthouse flag/ scan configuration/ whatever will require changes in the Audit class. Instead I think we should build the lighthouse parameters outside the Audit class, and inject it.
I think it will give more flexibility for more complex configurations, and less risk for regression bugs in the future.

**Describe the solution you'd like**
```
module.exports = class Audit {
  constructor(lighthouseConfig) {
    this.lighthouseConfig = lighthouseConfig || lighthouse.defaultConfig
    }
  }
  ...

    this.lighthouseConfig.opts.port =  this.lighthouseConfig.opts.port || chromeInstance.port
    debug(`invoking lighthouse scan for: ${url}`)
    const scanResult = await lighthouse(url,   this.lighthouseConfig.opts, this.lighthouseConfig.config);
....
```

**Describe alternatives you've considered**
Keep it the way it is:)

**Comment by lirantal** [comment]
I'm not entirely sure how this is a better approach though? you are still passing options to lighthouse's function call as far as I can see in that last line of code:
```
    const scanResult = await lighthouse(url,   this.lighthouseConfig.opts, this.lighthouseConfig.config);
```

**Comment by zivkaziv** [comment]
Just in order not to change `Audit class ` for every change of configuration. Make it more functional

**Comment by zivkaziv** [comment]
Again, lighthouse configuration can change much more then the `audit.scanUrl()`..

**Comment by lirantal** [comment]
yeah but why do we need to provide it in the function call `lighthouse()` if it is already provided to the constructor? I think that kind of refactor can be ok.

**Comment by lirantal** [comment]
Zvika I'll close this for now unless you'd want to pursue it later with some action where we can re-open it

**Comment by zivkaziv** [comment]
NP.. 
Thank you:)
