### ISSUE TITLE
Trim UTM_* from snyk URLs 

### ISSUE THREAD

**Issue by zivkaziv** [lirantal/is-website-vulnerable#35]
**Is your feature request related to a problem? Please describe.**
The current output set utm_* query params in the snyk vulnerabilities url.
For example:
```
 Website: https://www.microsoft.com/he-il/
  
    ⎡ ✖ jQuery@3.3.1
    ⎜ ■■■  1  vulnerabilities
    ⎣ ▶︎ https://snyk.io/vuln/npm:jquery?lh=3.3.1&utm_source=lighthouse&utm_medium=ref&utm_campaign=audit
  
  [1] Total vulnerabilities
  [7528.38ms] execution time
  vulnerabilities powered by Snyk.io (https://snyk.io/vuln?type=npm)
  ```
https://snyk.io/vuln/npm:jquery?lh=3.3.1**&utm_source=lighthouse&utm_medium=ref&utm_campaign=audit**

**Describe the solution you'd like**
Trim those utm_* query params from the URL

**Describe alternatives you've considered**

- Leave it as is..
- Create different query params

**Comment by lirantal** [comment]
Will be fixed by #38
