### ISSUE TITLE
Add a JSON output option

### ISSUE THREAD

**Issue by lirantal** [lirantal/is-website-vulnerable#4]
**Is your feature request related to a problem? Please describe.**
The default is to print out the results to the console but we could refactor the code to have multiple renderers, and add a `--json` flag to spit out the data in a JSON format.

**Comment by rajkumaar23** [comment]
I would like to contribute to this feature. Kindly assign me this ?

**Comment by lirantal** [comment]
Thanks a bunch! you got it 👍

**Comment by rajkumaar23** [comment]
Can you tell few sites that has vulnerabilities ? I couldn't find one.

**Comment by lirantal** [comment]
You mean to scan several sites? Nope, right now it supports just one URL.

**Comment by rajkumaar23** [comment]
No, I need an URL that has vulnerabilities. Whatever website I try, they all have 0 vulnerabilities.

**Comment by lirantal** [comment]
Oh I see what you mean, try this http://willhaben.at
You can easily grab a random one from the list of sites known to run old JS versions at https://w3techs.com/technologies/details/js-jquery/1/all

**Comment by rajkumaar23** [comment]
Hey, kindly review my pull request ?

**Comment by rajkumaar23** [comment]
Hey @lirantal ,  guess this issue can be closed.
