### ISSUE TITLE
Containerization for ease of use

### ISSUE THREAD

**Issue by darkwizard242** [lirantal/is-website-vulnerable#53]
**Is your feature request related to a problem? Please describe.**
It's not directly related to a problem, but I think that providing a Dockerfile for either building and running the container by themselves, or a docker image would be useful.

**Describe the solution you'd like**
I have already dockerized it's usage without having to install all the pre-requisites by the end users. I would like to request being added as contributor so that I can push a feature branch (with the Dockerfile) and create a pull request for master branch. Of course, the choice to approve or deny the Pull Request is all yours 😄 

**Describe alternatives you've considered**
1. Shell Scripts
2. Ansible

P.S Nothing else feels more isolated and easy to use than docker for is-website-vulnerable as it doesn't require being up all the time.

**Comment by lirantal** [comment]
Not sure why we have a duplicate, because there's this original issue #52 
Can you please chime in there and provide a Dockerfile in a PR? I'd love to merge it.
