### ISSUE TITLE
installing extraneous dependencies

### ISSUE THREAD

**Issue by travi** [lirantal/is-website-vulnerable#54]
i noticed some peer dependency warnings about semantic-release and got curious why my non-package project had semantic-release installed at all. it looks like your dev dependencies are getting installed for some reason.

## Expected Behavior

installing `is-website-vulnerable` should only install it and its production dependencies

## Current Behavior

even though semantic-release and its plugins are only listed as dev-dependencies, at least some of the dependencies are getting installed in my project:

```
$ npm ls @semantic-release/github
matt.travi.org@ /path/to/my/project/matt.travi.org
└─┬ is-website-vulnerable@1.9.3
  └── @semantic-release/github@5.5.5  extraneous
```

## Possible Solution

i havent used shrinkwrap much, but that is my best guess as to why this is happening. is it possible to only shrinkwrap prod dependencies?

## Steps to Reproduce (for bugs)

1. `npm install is-website-vulnerable --save-dev`
2. `npm ls @semantic-release/github` (or another dev-dependency)

## Context

i'm seeing peer-dependency warnings for dev-dependencies of this project that shouldnt have an impact on my project. i normally also enforce that `npm ls` exits with zero, which this would make fail. this particular does not fully enforce that yet, so this issue slipped through unnoticed originally

## Your Environment

- Library Version used: https://github.com/travi-org/matt.travi.org/blob/be7fa9cb6d70ca8ffee31df38bed187f706d88b2/package.json#L55
- Node.js version (e.g. Node.js 5.4): https://github.com/travi-org/matt.travi.org/blob/be7fa9cb6d70ca8ffee31df38bed187f706d88b2/.nvmrc#L1 (currently 10.17.2)
- Operating System and version (desktop or mobile): macOS catalina 10.15.2

**Comment by lirantal** [comment]
ahh, good catch, it is due to the shrinkwrap. will take a look at fixing this, thanks!

**Comment by lirantal** [comment]
@travi which npm cli version are you running?

**Comment by travi** [comment]
I'm just using the version installed with the version of node mentioned above. I'm afk atm, but can confirm in a bit

**Comment by travi** [comment]
Regardless of whether dev dependencies _should_ be installed or not, the warnings i see after they do get installed in my project highlight that _your_ peer dependencies aren't compatible ;)

It looks like you're using the `beta` of semantic-release, but `latest` of the plugins. You should be using the pre-releases of those too. `npm ls` should help identify a compatible combination

**Comment by travi** [comment]
So if those were resolved, it would at least prevent warnings on my side. While i agree that it's odd that shrinkwrap installs the dev dependencies, i don't necessarily mind if it doesn't cause errors

**Comment by lirantal** [comment]
yep, I see those now too.
let's figure out first the shrinkwrap issue as I'd need to update that with any change regardless.

**Comment by lirantal** [comment]
@travi can you try with the latest stable Node.js, or npm version `6.12.1` ?
I don't get peer dependency issues with it

**Comment by lirantal** [comment]
Nevermind, I do see it. The npm CLI is weird as it skipped those in the first install but running another install after everything is installed they will show up 🤷‍♂

**Comment by lirantal** [comment]
@travi can you check now if you're still getting peer deps issues?

**Comment by travi** [comment]
so, unfortunately, it doesn't seem to be available yet:

```
$ npm dist-tags ls is-website-vulnerable
latest: 1.9.3 
```

i had a package [publish earlier today](https://github.com/travi-org/matt.travi.org-components/releases/tag/v3.1.7) that is still not available either. i sent a note to support earlier today, but the [status page](https://status.npmjs.org/) doesnt note any issues.

**Comment by travi** [comment]
at least i wasnt crazy: https://status.npmjs.org/incidents/lg9535dl2ff3

i'll keep an eye on the incident and test once it gets resolved

**Comment by travi** [comment]
now that i could install the new version, i was able to confirm that the peer-dependency issues look good, but `npm ls` does still complain about the extraneous dev-dependencies, and therefore exits with `1` instead of `0`

**Comment by lirantal** [comment]
Yep, will see about fixing that.

**Comment by travi** [comment]
been a while since i've looked into this, so trying to remember where this landed. did we end up figuring out a way to sort out the shrinkwrap issues, or are we stuck in the state where devDependencies are getting wrapped until npm v7 is available?

**Comment by lirantal** [comment]
Indeed still need to work on this. Let me get to review this again.

**Comment by lirantal** [comment]
@travi is-website-vulnerable@1.14.1 fixes the issue now thanks to lockfile-prune

**Comment by travi** [comment]
Great work! Looks like that did it. Thanks a lot!
