### ISSUE TITLE
An empathic CLI 🤗 if no input provided use a prompt

### ISSUE THREAD

**Issue by lirantal** [lirantal/is-website-vulnerable#56]
**Is your feature request related to a problem? Please describe.**
I like highly empathic CLIs, so for example, instead of failing when there’s no URL provided perhaps we could use something like inquirer (or lighter package if exists, or just... Node.js core APIs? :-) ) that if no input is provided we prompt the user for it and then scan. Basically taking the frustration out of the process of using the CLI.

**Describe the solution you'd like**
Described above

**Describe alternatives you've considered**
None

**Comment by itaisteinherz** [comment]
I'd like to work on this :)
