### ISSUE TITLE
Add support for printing out detected JS libraries

### ISSUE THREAD

**Issue by lirantal** [lirantal/is-website-vulnerable#6]
**Is your feature request related to a problem? Please describe.**
While not particularly showing vulnerabilities but lighthouse also exposes an audit called `'js-libraries'` which details the detected (if any) JS libraries. We could print them out as extra meta data tool

**Describe the solution you'd like**
This will probably require a bit more goofing around work with the data from lighthouse so be prepared for that. Ideally we'd also need to add a flag such as `--js-libs` or something to add this metadata.

**Comment by DanielRuf** [comment]
See https://github.com/DanielRuf/website-stack/blob/master/index.js and https://github.com/AliasIO/Wappalyzer for some ideas ;-)

**Comment by Cardoso222** [comment]
I'm on it!

**Comment by lirantal** [comment]
Closed by #29
