### ISSUE TITLE
Feat: refactor bin/is-website-vulnerable.js

### ISSUE THREAD

**Issue by lirantal** [lirantal/is-website-vulnerable#60]
**Describe the solution you'd like**

Looks like https://github.com/lirantal/is-website-vulnerable/blob/master/bin/is-website-vulnerable.js had grown quite a bit. Let's refactor it? there are some clear separation of concerns there that can apply.

**Comment by juanpicado** [comment]
I can do this :)

**Comment by lirantal** [comment]
Thanks Juan, next time! :-)

**Comment by VictorZubr** [comment]
I opened a new PR.

**Comment by lirantal** [comment]
Thanks I'll follow-up with that one!

**Comment by lirantal** [comment]
Fixed by #62
