### ISSUE TITLE
Scan errors out with PROTOCOL_TIMEOUT

### ISSUE THREAD

**Issue by Ryuno-Ki** [lirantal/is-website-vulnerable#73]
On Ubuntu in a corporate network
When I scan my employer's homepage (https://jambit.com/)
AND I turn `DEBUG=*` on,
Then I can see a start of the audit:
https://github.com/lirantal/is-website-vulnerable/blob/492bd53a8d497a2efc6654c4e92be248107e8379/src/Audit.js#L88-L91
And a timeout with `PROTOCOL_TIMEOUT` after a while (30 seconds?).

This does not happen when running the code
`npx is-website-vulnerable https://jambit.com/` from home.

Looks like it were caused by https://github.com/GoogleChrome/lighthouse/issues/6512 but this npm package might need to handle the error gracefully.

I haven't took time to clone the repo and run a local build.

**Comment by lirantal** [comment]
Thanks @Ryuno-Ki for the detailed report 👍
Indeed I think we just need to detect and gracefully handle with a descriptive error message

**Comment by rajkumaar23** [comment]
Can I take this up? @lirantal

**Comment by lirantal** [comment]
@rajkumaar23 definitely, thank you ❤️
