### ISSUE TITLE
Console error code of 2 during successful commands?

### ISSUE THREAD

**Issue by famouspotatoes** [lirantal/is-website-vulnerable#74]
Not sure if this is the intended behavior, but when I run the command successfully, it still outputs a console error code of "2". If I understand correctly, a successful command should output "0" for successful executions.

Is this the correct behavior?

If desired I can fill out the full bug report, but I figured a quick post would be better to address this small issue.

Otherwise thanks for the awesome package!

**Comment by rajkumaar23** [comment]
So, basically the command will exit with a status code of **2** if the website you're trying to run the command against has vulnerabilities.
https://github.com/lirantal/is-website-vulnerable/blob/492bd53a8d497a2efc6654c4e92be248107e8379/bin/is-website-vulnerable.js#L62-L63

**Comment by famouspotatoes** [comment]
Ok thanks for letting me know. Is there an exit status code for unsuccessful commands (such as the website DNS records could not be found)?

**Comment by rajkumaar23** [comment]
Yes, it is **1**
https://github.com/lirantal/is-website-vulnerable/blob/492bd53a8d497a2efc6654c4e92be248107e8379/bin/is-website-vulnerable.js#L68-L70

**Comment by lirantal** [comment]
Thanks Raj for picking up this one!

**Comment by Ryuno-Ki** [comment]
Should we document those Exit codes in the README, @lirantal?

**Comment by lirantal** [comment]
@Ryuno-Ki yes, sounds like a great idea!
Can you open a PR to add?

**Comment by Ryuno-Ki** [comment]
At your command: #81
