### ISSUE TITLE
Spelling error in code

### ISSUE THREAD

**Issue by rajkumaar23** [lirantal/is-website-vulnerable#77]
I'm just curious why **authentication** was misspelled in the code. Was it intentional ? If not, I can make a PR fixing this one.
https://github.com/lirantal/is-website-vulnerable/blob/6db48335e7d688a17af9e2747db201b8df49c1c3/src/Utils.js#L46

**Comment by lirantal** [comment]
Indeed a typo ;-)

**Comment by lirantal** [comment]
A fix would be great!
