### ISSUE TITLE
not being quiet can you please supress these few messages during quiet

### ISSUE THREAD

**Issue by devcoinfet** [lirantal/is-website-vulnerable#79]
npx: installed 301 in 5.888s

i can deal with this one at the least but these 2 i would like it if you could remove them in quiet mode for us

Error: Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Details: net::ERR_CERT_COMMON_NAME_INVALID)

Usage:
  is-website-vulnerable https://www.google.com

**Comment by devcoinfet** [comment]
so total there is only two im sorry never mind the npx ill get rid of that so that ssl error is all im worried about as its in my output

**Comment by lirantal** [comment]
Well there's no "quiet mode" option yet, and that error is coming from lighthouse itself.
What would you expect to happen/see if there are errors?

Can you give me an example URL I can use to reproduce the issue?

**Comment by devcoinfet** [comment]
ok ill look into lighthouse

**Comment by devcoinfet** [comment]
https://github.com/GoogleChrome/lighthouse/issues/559


ill close it as this is my isue underlying during bounty scan i believe

**Comment by lirantal** [comment]
👍
