### ISSUE TITLE
Error: getaddrinfo ENOTFOUND localhost undefined:58866

### ISSUE THREAD

**Issue by Celia-SSS** [lirantal/is-website-vulnerable#80]
npm -i is-website-vulnerable -g

is-website-vulnerable https://example.com 
[   =] Setting up a chrome instance
Error: getaddrinfo ENOTFOUND localhost undefined:58866

Usage:
  is-website-vulnerable https://www.google.com

**Comment by Ryuno-Ki** [comment]
Can't reproduce:

```
is-website-vulnerable https://example.com
✔ Set up completed in 1.09 seconds!
✔ Auditing completed in 2.93 seconds!

  Website: https://example.com/
  ○ No JavaScript libraries detected with publicly known security vulnerabilities
  
  [0] Total vulnerabilities
  [2720.96ms] execution time
  vulnerabilities powered by Snyk.io (https://snyk.io/vuln?type=npm)
```

What version are you using? (`is-website-vulnerable --version`)

**Comment by lirantal** [comment]
@Celia-SSS any notes or should we close?
