### ISSUE TITLE
WSL 2 connect ECONNREFUSED 127.0.0.1:41299

### ISSUE THREAD

**Issue by MontoyaAndres** [lirantal/is-website-vulnerable#83]
I just copy and paste the example on the README and tried on WSL 2 Ubuntu and I got this response:

![image](https://user-images.githubusercontent.com/15065852/97792712-b41da300-1baf-11eb-8c58-db321675f35d.png)

## Expected Behavior

Get the correct results.

- Library Version used: latest version downloaded with npx
- Node.js version (e.g. Node.js 5.4): 14.15.0
- Operating System and version (desktop or mobile): Windows 10 WSL 2

**Comment by Ryuno-Ki** [comment]
I'm not using Windows (nor WSL).
Researching on the web suggested, that `wsl --shutdown` and reopening the terminal „solved” it for some people (temporarily).

I *think* I've seen a former colleague using a service (netstat?) to list the ports in use.
We're not allowing to pick another port (yet?), but this could give an indicator, whether another service is already listening on that port.

Do you have another Chrome headless running perhaps?
Maybe, that one didn't shut down properly …

**Comment by MontoyaAndres** [comment]
Mmmm I don't know if I have another Chrome headless running 😅

**Comment by Ryuno-Ki** [comment]
There's a process / task manager in Windows. Does it show processes in WSL, too?
For Linux, it would be `ps aux | grep chrome`, I think.

**Comment by lirantal** [comment]
Indeed we haven't tested this with WSL. If it has resolved for you @MontoyaAndres let us know.
