### ISSUE TITLE
If Chrome is not available, can Edge be used?

### ISSUE THREAD

**Issue by pysiak** [lirantal/is-website-vulnerable#87]
I have had is-website-vulnerable installed when I had Chrome. Company moved from Chrome to Edge and I don't have Chrome any longer.
Edge is Chromium-based. Can is-website-vulnerable fallback to Edge when Chrome is not found?

**Describe the solution you'd like**
If possible, check for Chrome first, then Edge. Perhaps as experimental feature, without support if there are breaking differences. I don't want to suggest something that would increase the support surface of the tool if it's too much.
But if it's just fine then why not?

**Describe alternatives you've considered**
I can install Chrome, but it'd be additional software to install, while my users use Edge.

Thanks for your attention,
Maciej

**Comment by lirantal** [comment]
Not currently since lighthouse is part of the Chrome DevTools.
Edge has WebHint however which does support similar security vulnerabilities findings from Snyk but it would require updates to the code. If you're able to whip it up I'm happy to accept a pull request.
