### ISSUE TITLE
JSON Output when running docker

### ISSUE THREAD

**Issue by SamShanks1** [lirantal/is-website-vulnerable#88]
I don't know if this is already a thing, if it is I couldnt work out how to use it but is it possible to use the --json output when running it in a docker container?

**Comment by Ryuno-Ki** [comment]
I'm curious, how would you want to process it further? What's the Big Picture?

**Comment by SamShanks1** [comment]
So I was using the npx scan to get the JSON result then process this into a database with the vulnerabilities, however I have moved it all to azure so I can automate the scans using a container instance the problem is the output I get is just the default output. I was just thinking maybe theres a way where you can add a parameter when running the container that would change the output to json.

**Comment by lirantal** [comment]
@SamShanks1 I pushed a new version of the image for you which supports now command arguments to be passed.

The normal and existing behavior right now is:

```
docker run --rm -e SCAN_URL="https://www.google.com/" lirantal/is-website-vulnerable:latest
```

Which works as is.
If you wish to pass arguments then you need to also specify the URL and everything else to is-website-vulnerable, such as:

```
docker run --rm lirantal/is-website-vulnerable:latest https://www.google.com --json
```
