### ISSUE TITLE
check private github pages

### ISSUE THREAD

**Issue by jeising** [lirantal/is-website-vulnerable#90]
To check private github pages their might be a need to access the website via login or token. Is there a way to do this with this action?

**Comment by lirantal** [comment]
Good question!

There's a `--cookie` option that you can use.
See PR here: https://github.com/lirantal/is-website-vulnerable/pull/67

**Comment by jeising** [comment]
I ended up using python http server to serve the website and use your docker run command with network is host to check the website. This has the benefit that a branch can be checked before it goes to master. Maybe there could be an option in the gh action to allow access to port 8000 (standard port for python http server) than I could use the gh action again. One downside is that I needed to use a sleep to wait till python has the website ready. But all in all I like the solution and would consider this issue closed.

**Comment by lirantal** [comment]
Thanks, glad to hear it worked out.
