### ISSUE TITLE
Error: perf.getEntriesByName is not a function on npx run

### ISSUE THREAD

**Issue by ibrahimcesar** [lirantal/is-website-vulnerable#92]
## Expected Behavior
- Return report from the url provided

## Current Behavior

- Throws error `perf.getEntriesByName is not a function`

## Possible Solution

- Didn't debugged

## Steps to Reproduce (for bugs)

1. Used the command `npx is-website-vulnerable <url>`
2. Accepted install from npm
3. Returns error with Usage

## Context

```bash
❯ npx is-website-vulnerable https://www.nexojornal.com.br
Need to install the following packages:
  is-website-vulnerable
Ok to proceed? (y) y
✔ Set up completed in 9.20 seconds!
[    ] Auditing...
Error: perf.getEntriesByName is not a function

Usage:
  is-website-vulnerable https://www.google.com

❯ npx is-website-vulnerable https://www.google.com
✔ Set up completed in 6.35 seconds!
[    ] Auditing...
Error: perf.getEntriesByName is not a function

Usage:
  is-website-vulnerable https://www.google.com
```

## Your Environment

- Library Version used:
- Node.js v16.0.0
- Npm v7.12.0
- macOS Big Sur 11.4 Desktop
- `npm install -g is-website-vulnerable` has the same problem

**Comment by ibrahimcesar** [comment]
Thanks to you @lirantal ! Great tool! Thanks for the fast response! No pressure, and great work!

**Comment by lirantal** [comment]
I'm using macOS too but on a previous version (10) which works ok here so I can't reproduce immediately: 
![image](https://user-images.githubusercontent.com/316371/123124979-cc00aa80-d450-11eb-8f22-3151bae08c19.png)

**Comment by ibrahimcesar** [comment]
No pressure, and thanks a lot for the report 😀!

**Comment by lirantal** [comment]
Ok I was able to replicate this with Node.js 16 and npm7 🙃 
If you're able to get back to npm6 then it'll probably fix it, but otherwise I'll take a look further and see what hassle it has with the package versions

**Comment by lirantal** [comment]
https://github.com/GoogleChrome/lighthouse/issues/12439#issue-875596522

**Comment by lirantal** [comment]
@ibrahimcesar latest version should work now with Node.js 16 (due to an indirect dependency on `marky` which was the issue).

You probably need to wait a bit for `npx` to pull in the new version from the registry, or just try it out and see if it's already working for you :)
